ALTER TABLE items ADD COLUMN sku TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN quantity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN price REAL NOT NULL DEFAULT 0.0;
ALTER TABLE items ADD COLUMN tags TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN image_path TEXT;
CREATE INDEX IF NOT EXISTS idx_items_sku ON items(sku);
