// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Item = { id: string, name: string, description: string | null, is_active: boolean, created_at: string, updated_at: string, };
