// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateItemInput = { name: string | null, description: string | null, sku: string | null, quantity: number | null, price: number | null, tags: string | null, image: string | null, is_active: boolean | null, };
